language: node_js
node_js: --lts
before_script:
  - git config user.name "Imccccc"
  - git config user.email "zqasder@gmail.com"
  - sed -i'' "s~https://github.com/Imccccc/Imccccc.github.io.git~https://${GITHUB_ACCESS_TOKEN}@github.com/Imccccc/Imccccc.github.io.git~" _config.yml
script:
  - hexo g
  - hexo d

